name: flutter_deer driver

#Conditions for triggering workflow
on: [push, pull_request]

#One or more tasks performed by workflow
jobs:
 ...
 #Trigger to modify 'pubspec. Yaml' in push submission
on:
  push:
    paths:
      - 'pubspec.yaml'
 ...
jobs:
  #The task ID must be unique under jobs
  accessibility_test: 
    #The virtual machine environment required to run. For example, windows-2019, MacOS latest, macos-10.14
    runs-on: macos-latest
    #Running steps of job
    steps:
      #It is easy to get the source code of flutter
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      #Setting up the flutter environment
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'
          channel: 'stable'  # or: 'dev' or 'beta'
        #Command to run
      - run: "flutter pub get"
        #Step name
      - name: "Run Flutter Accessibility Tests"
        run: "flutter test test/accessibility_test.dart"
        drive_ios:
    #Create a construction matrix
    strategy:
      #Set up different configurations for a set of virtual environments
      matrix:
        device:
          - "iPhone 8 (14.4)"
          - "iPhone 11 Pro Max (14.4)"
      #When set to true, GitHub cancels all in progress jobs if any of the matrix jobs fail.
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: "List all simulators"
        run: "xcrun instruments -s"
      - name: "Start Simulator"
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          Flitter version: '2.0.2'? Specifies the flitter environment
          channel: 'stable'
      - name: "Run Flutter Driver tests"
        run: "flutter drive --target=test_driver/driver.dart"
        
        drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'
          channel: 'stable'
      - name: "Run Flutter Driver tests"
        #Operation for installing, configuring and running Android emulator (MAC OS only)
        # https://github.com/marketplace/actions/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: "flutter drive --target=test_driver/driver.dart"
           web_build_and_deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'
          channel: 'stable'
      - name: "Web Build ?"
        run: |
          flutter pub get
          flutter build web
      - name: "Web Deploy ?"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          branch: gh-pages
          folder: build/web
          
        
